# Generated by Django 6.1.1 on 2026-09-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='catalog.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_previstas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade_prevista', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_previsto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('prazo_previsto', models.DateField(blank=True, null=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='catalog.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='catalog.equipamento')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='catalog.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoEquipamentoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_equipamentos', to='catalog.atividade')),
                ('projeto_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='catalog.projetoequipamento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.UniqueConstraint(fields=('cliente', 'codigo'), name='unique_projeto_cliente_codigo'),
        ),
        migrations.AddConstraint(
            model_name='projetoequipamento',
            constraint=models.UniqueConstraint(fields=('projeto', 'equipamento'), name='unique_projeto_equipamento'),
        ),
        migrations.AddConstraint(
            model_name='projetoequipamentoatividade',
            constraint=models.UniqueConstraint(fields=('projeto_equipamento', 'atividade'), name='unique_projeto_equipamento_atividade'),
        ),
    ]
