# Generated by Django 6.1.1 on 2026-09-28 22:54

from django.db import migrations

def create_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Técnico de Campo')
    Group.objects.get_or_create(name='Planejador/Analista')

def delete_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Técnico de Campo', 'Planejador/Analista']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_colaborador_usuario"),
    ]

    operations = [
        migrations.RunPython(create_roles, delete_roles),
    ]
