# Generated by Django 6.1.1 on 2026-10-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_create_bi_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetoequipamentoatividade",
            name="desvio_tempo_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Desvio percentual entre estimado e real",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projetoequipamentoatividade",
            name="tempo_medio_estimado",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Tempo manual inicial previsto por unidade em horas",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="projetoequipamentoatividade",
            name="tempo_medio_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tempo médio real calculado a partir de apontamentos aprovados",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projetoequipamentoatividade",
            name="total_amostras",
            field=models.IntegerField(
                default=0,
                help_text="Total de apontamentos aprovados considerados no cálculo",
            ),
        ),
    ]
