# Generated by Django 6.1.1 on 2026-09-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apontamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot do custo-hora no momento do apontamento', max_digits=10)),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='EM_ANALISE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.atividade')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.equipamento')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.projeto')),
            ],
        ),
    ]
